// <auto-generated />
using System;
using AgriConnect.Api.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.src.migrations
{
    [DbContext(typeof(AgriConnectDbContext))]
    [Migration("20260925085221_AddSharedAuditLogNotificationTables")]
    partial class AddSharedAuditLogNotificationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriConnect.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_AuditLog_ActorId");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_AuditLog_EntityId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLog_Timestamp");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("AgriConnect.Api.Models.CollectionCentre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("IX_CollectionCentre_RegionId");

                    b.ToTable("CollectionCentre", null, t =>
                        {
                            t.HasCheckConstraint("CK_CollectionCentre_Capacity", "\"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("AgriConnect.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notification_UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("AgriConnect.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryPreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("IX_Order_BuyerId");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("IX_Order_ListingId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Order_Status");

                    b.ToTable("Order", null, t =>
                        {
                            t.HasCheckConstraint("CK_Order_DeliveryPreference", "\"DeliveryPreference\" IN ('Pickup','Delivery')");

                            t.HasCheckConstraint("CK_Order_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Order_Status", "\"Status\" IN ('Pending','Approved','Scheduled','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("AgriConnect.Api.Models.PickupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionCentreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SlotEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SlotStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_PickupSchedule_OrderId");

                    b.HasIndex("CollectionCentreId", "SlotStart", "SlotEnd")
                        .IsUnique()
                        .HasDatabaseName("IX_PickupSchedule_Centre_Slot_Confirmed")
                        .HasFilter("\"Status\" = 'Confirmed'");

                    b.ToTable("PickupSchedule", null, t =>
                        {
                            t.HasCheckConstraint("CK_PickupSchedule_SlotWindow", "\"SlotEnd\" > \"SlotStart\"");

                            t.HasCheckConstraint("CK_PickupSchedule_Status", "\"Status\" IN ('Proposed','Confirmed','Cancelled')");
                        });
                });

            modelBuilder.Entity("AgriConnect.Api.Models.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_StockReservation_ExpiresAt");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("IX_StockReservation_ListingId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockReservation_OrderId");

                    b.ToTable("StockReservation", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockReservation_ReservedQuantity", "\"ReservedQuantity\" > 0");
                        });
                });

            modelBuilder.Entity("AgriConnect.Api.Models.PickupSchedule", b =>
                {
                    b.HasOne("AgriConnect.Api.Models.CollectionCentre", "CollectionCentre")
                        .WithMany("PickupSchedules")
                        .HasForeignKey("CollectionCentreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriConnect.Api.Models.Order", "Order")
                        .WithOne("PickupSchedule")
                        .HasForeignKey("AgriConnect.Api.Models.PickupSchedule", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionCentre");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AgriConnect.Api.Models.StockReservation", b =>
                {
                    b.HasOne("AgriConnect.Api.Models.Order", "Order")
                        .WithOne("StockReservation")
                        .HasForeignKey("AgriConnect.Api.Models.StockReservation", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AgriConnect.Api.Models.CollectionCentre", b =>
                {
                    b.Navigation("PickupSchedules");
                });

            modelBuilder.Entity("AgriConnect.Api.Models.Order", b =>
                {
                    b.Navigation("PickupSchedule");

                    b.Navigation("StockReservation");
                });
#pragma warning restore 612, 618
        }
    }
}
